name: umi-pipeline-nf
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - snakemake-minimal
  - minimap2
  - samtools
  - seqkit
  - pysam
  - bedtools
  - vsearch
  - varscan
  - medaka==1.1.3
  - pip
  - pip:
    - catfishq
    - numpy==1.19.5
    - pysam
    - tqdm
    - pandas
    - seaborn
    - edlib
# removed all dependencies from template pipeline