name: umi-pipeline-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.6
  - snakemake-minimal
  - minimap2
  - samtools
  - seqtk
  - lofreq
  - freebayes
  - whatshap
  - seqkit
  - pysam
  - bedtools
  - vsearch
  - varscan
  - medaka
  - openjdk=11.0.9
  - unzip
  - pip
  - pip:
    - catfishq
    - numpy
    - pysam
    - tqdm
    - pandas
    - seaborn
    - edlib

